[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ndgnuh-dev-env"
version = "1.0.0"
dependencies = []

[project.scripts]
enter-dev="src.enterdev:main"
